### ISSUE TITLE
[mbed-3185] ERROR: Exceeded 5 minutes limit while waiting for other process to finish caching

### ISSUE THREAD

**Issue by ggscuola** [ARMmbed/mbed-cloud-client-yocto-setup#21]
Hi
this is y first time with mbed.I followed this guide:https://cloud.mbed.com/docs/current/connecting/linux-on-raspberry-pi-3.html
below my message output console:

$git clone https://github.com/ARMmbed/mbed-cloud-client-yocto-setup
Cloning into 'mbed-cloud-client-yocto-setup'...
remote: Enumerating objects: 259, done.
remote: Total 259 (delta 0), reused 0 (delta 0), pack-reused 259
Receiving objects: 100% (259/259), 58.73 KiB | 572.00 KiB/s, done.
Resolving deltas: 100% (79/79), done.
$ cd mbed-cloud-client-yocto-setup/
$ mbed deploy -vv
[mbed-3185] Working path "/media/xxx/WORKDIR/YOCTOMBED/mbed-cloud-client-yocto-setup" (program)
[mbed-3185] Exec "git remote -v" in "/media/xxx/WORKDIR/YOCTOMBED/mbed-cloud-client-yocto-setup"
origin	https://github.com/ARMmbed/mbed-cloud-client-yocto-setup (fetch)
origin	https://github.com/ARMmbed/mbed-cloud-client-yocto-setup (push)
[mbed-3185] Exec "git rev-parse HEAD" in "/media/xxx/WORKDIR/YOCTOMBED/mbed-cloud-client-yocto-setup"
984c7bdc1e7b15d5eca3997737fd75138fc43471
[mbed-3185] Adding library "poky" from "git://git.yoctoproject.org/poky" at rev #d240b885f26e
[mbed-3185] Trying to guess source control management tool. Supported SCMs: bld, git, hg
[mbed-3185] Found matching cached repository in "/home/xxx/.mbed/mbed-cache/git.yoctoproject.org/poky"
[mbed-3185] Carbon copy from "/home/xxx/.mbed/mbed-cache/git.yoctoproject.org/poky" to "/media/xxx/WORKDIR/YOCTOMBED/mbed-cloud-client-yocto-setup/poky"
[mbed-3185] ERROR: Exceeded 5 minutes limit while waiting for other process to finish caching

**Comment by teetak01** [comment]
HI @ggscuola could you try running it as:

`time mbed deploy --protocol git -v`

**Comment by ggscuola** [comment]
It's the same, I tried a lot of times:
$ time mbed deploy --protocol git -v
[mbed] Working path "/media/xxx/WORKDIR/YOCTOMBED/mbed-cloud-client-yocto-setup" (program)
[mbed] Adding library "poky" from "git://git.yoctoproject.org/poky" at rev #d240b885f26e
[mbed] Trying to guess source control management tool. Supported SCMs: bld, git, hg
[mbed] Found matching cached repository in "/home/xxx/.mbed/mbed-cache/git.yoctoproject.org/poky"
[mbed] Carbon copy from "/home/xxx/.mbed/mbed-cache/git.yoctoproject.org/poky" to "/media/xxx/WORKDIR/YOCTOMBED/mbed-cloud-client-yocto-setup/poky"
[mbed] ERROR: Exceeded 5 minutes limit while waiting for other process to finish caching
---

real	4m59,502s
user	0m0,151s
sys	0m0,042s

**Comment by ggscuola** [comment]
I tried also by option --cache on

**Comment by ggscuola** [comment]
I think that is some thread locked on cache, but I dont have any idea to resolve it.

I removed the folder of git clone mbed-cloud-client-yocto-setup, and I repeated steps by another clone. The result is the same

**Comment by ggscuola** [comment]
dear @teetak01 it seem solved with this command before deploy:
 sudo mbed cache off

now this is the final messages: WHat does it mean this WARNING, I need download something?

**mbed] Exec "git checkout 2bb21ef27c4b0c9d52d30b3b2c5a0160fd02b966 -f -q" in "/media/xxx/WORKDIR/YOCTOMBED/mbed-cloud-client-yocto-setup/layers/meta-openembedded"
[mbed] WARNING: Cannot find the mbed tools directory in "/media/xxx/WORKDIR/YOCTOMBED/mbed-cloud-client-yocto-setup"**
---

real	1m7,450s
user	0m23,499s
sys	0m5,257s

**Comment by teetak01** [comment]
Hi @ggscuola good to know that turning off the caching resolved it. You can ignore the warning about mbed tools. That is part of Mbed OS, and because the yocto build does not use Mbed OS, the deployment tool complains about it.

**Comment by teetak01** [comment]
This part "real	4m59,502s" show that for some reason the caching took more than the hardcoded 5 minute timeout. That is something the mbed-cli team needs to take look at.

Do you mind raising an issue to mbed-cli repository or do you want me to report this issue?

**Comment by ggscuola** [comment]
Yes if uou can do it, it ia better. ThanksInviato dal mio dispositivo mobile Huawei-------- Messaggio originale --------Oggetto: Re: [ARMmbed/mbed-cloud-client-yocto-setup] [mbed-3185] ERROR: Exceeded 5 minutes limit while waiting for other process to finish caching (#21)Da: Teemu Takaluoma A: ARMmbed/mbed-cloud-client-yocto-setup CC: ggscuola ,Mention This part "real	4m59,502s" show that for some reason the caching took more than the hardcoded 5 minute timeout. That is something the mbed-cli team needs to take look at.
Do you mind raising an issue to mbed-cli repository or do you want me to report this issue?

**Comment by teetak01** [comment]
Reported an issue on the tooling side: https://github.com/ARMmbed/mbed-cli/issues/856

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-3375
