### ISSUE TITLE
ubuntu pc freeze at number pck 272 of 310 - it's necessary rebootby pushbutton

### ISSUE THREAD

**Issue by ggscuola** [ARMmbed/mbed-cloud-client-yocto-setup#22]
Hi
after this command:
make -f Makefile.example EXTRA_CONF_FILE=1 build-raspberry-example
(I tried also without EXTRA_CONF_FILE)
system start building with meta recipes of several layers 

When compilation arrives about 80%, on 272/310 completed pck. compilation blocks my PC completely.
In this moment only 2 thread are running on cpu, one of them is binutils-cross_2.30.bb:do_compile.
the other one is armgcc cross compiler.
I dont have any screenshot because my PC was freezed. 
This issue is not random, I tried 4 times, also using different number of processors on running.

I use: ASUS PC - Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04 
Codename:	bionic
kernel 4.15.0-45
I already know that this release ubuntu is not suggested, but I know from others developers use this 18.04 for yocto and mbed os linux.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-3376

**Comment by teetak01** [comment]
@ggscuola thanks for reporting the issue.

**Comment by teetak01** [comment]
Hi @ggscuola the latest release 3.2.0 did some improvements on the yocto-side, and I also verified that Ubuntu 18.04 (inside virtual machine) builds fine.

The issue reported here seems to be more of a feature of yocto build system. It can be very intensive on the build machine, and can also take several hours when building from scratch.

**Comment by teetak01** [comment]
Closing as fixed. Please reopen, if issues remain.
