### ISSUE TITLE
A poky build issue in git.py

### ISSUE THREAD

**Issue by yemkay** [ARMmbed/mbed-cloud-client-yocto-setup#6]
This is not an issue in this repo, but in poky. This change is necessary in poky/bitbake/lib/bb/fetch2/git.py

```
- runfetchcmd("%s branch --set-upstream %s origin/%s" % (ud.basecmd, branchname, \
+ runfetchcmd("%s branch %s --set-upstream-to origin/%s" % (ud.basecmd, branchname, \
```
	
https://patchwork.openembedded.org/patch/145072/

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2677

**Comment by teetak01** [comment]
Hi @yemkay, we will check this.

**Comment by yemkay** [comment]
Thank you. This error happenned Ubuntu 18.04. When I retried on Ubuntu 16.04, it worked fine.

**Comment by JaniSuonpera** [comment]
Hi @yemkay 

Current Rasperry PI Yocto build is using Morty/Yocto 2.2. There are available supported Linux distros https://www.yoctoproject.org/docs/2.2/ref-manual/ref-manual.html#detailed-supported-distros. This failure with Ubuntu 18.04 is limitation with used Yocto branch.

We are going to update this repository to use newer Yocto branch future.  I see that we must add some reference to documentation about Yocto branch and supported Linux distributions.

**Comment by JaniSuonpera** [comment]
I have made some clarification to https://cloud.mbed.com/docs/current/connecting/linux-on-raspberry-pi-3.html. Please check details and use some of supported Linux distribution for compiling Yocto images.
