### ISSUE TITLE
build error: conflicting types for ‘copy_file_range’

### ISSUE THREAD

**Issue by yemkay** [ARMmbed/mbed-cloud-client-yocto-setup#7]
Any clues about this build error? 

`
| ../../git/debugfs/../misc/create_inode.c: At top level:
**| ../../git/debugfs/../misc/create_inode.c:395:18: error: conflicting types for ‘copy_file_range’
|  static errcode_t copy_file_range(ext2_filsys fs, int fd, ext2_file_t e2_file,**
|                   ^~~~~~~~~~~~~~~
| In file included from ../../git/debugfs/../misc/create_inode.c:19:0:
| /usr/include/unistd.h:1110:9: note: previous declaration of ‘copy_file_range’ was here
|  ssize_t copy_file_range (int __infd, __off64_t *__pinoff,
|          ^~~~~~~~~~~~~~~
| Makefile:412: recipe for target 'create_inode.o' failed
| make[2]: *** [create_inode.o] Error 1
| make[2]: Leaving directory '/mbed-cloud-client-yocto-setup/rpi-build/tmp/work/x86_64-linux/e2fsprogs-native/1.43-r1/build/debugfs'
| Makefile:399: recipe for target 'all-progs-recursive' failed
| make[1]: *** [all-progs-recursive] Error 1
| make[1]: Leaving directory '/mbed-cloud-client-yocto-setup/rpi-build/tmp/work/x86_64-linux/e2fsprogs-native/1.43-r1/build'
| Makefile:334: recipe for target 'all' failed
| make: *** [all] Error 2
| ERROR: Function failed: do_compile (log file is located at /mbed-cloud-client-yocto-setup/rpi-build/tmp/work/x86_64-linux/e2fsprogs-nativ
e/1.43-r1/temp/log.do_compile.22965)
ERROR: Task (virtual:native:/mbed-cloud-client-yocto-setup/poky/meta/recipes-devtools/e2fsprogs/e2fsprogs_1.43.bb:do_compile) failed with e
xit code '1'
NOTE: Tasks Summary: Attempted 1714 tasks of which 1704 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  virtual:native:/mbed-cloud-client-yocto-setup/poky/meta/recipes-devtools/e2fsprogs/e2fsprogs_1.43.bb:do_compile
Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
Makefile.example:9: recipe for target 'build-raspberry-example' failed
`

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2684

**Comment by teetak01** [comment]
Hi @yemkay we have not encountered this, but it might be related to #6 that might get fixed with later version of Yocto. We will look in to this.

**Comment by yemkay** [comment]
This error may be specific on latest Ubuntu. I tried the same Ubuntu version as you and didn't get this error. I had to still make some tweaks, which I will capture in another issue. Closing this. Thank you!!

**Comment by PureBasic** [comment]
Hello all,
Error confirmed on Ubuntu 18.04 server.

Any workaround ? I don't have a 14.04 machine ready to run (and I'm out of coffee).

**Comment by teetak01** [comment]
This issue is quite old. If there is some new issues with latest relese, please open a new issue for that.

I am currently using Ubuntu 18.04 myself, and have not seen this issue with that version either.

**Comment by PureBasic** [comment]
Okay thanks @teetak01
