### ISSUE TITLE
Few tweaks to get the build complete on Ubuntu 16.04

### ISSUE THREAD

**Issue by yemkay** [ARMmbed/mbed-cloud-client-yocto-setup#8]
Disclaimer: I'm not familiar with Yocto, so just looked up the tweaks online.

```
| /mbed-cloud-client-yocto-setup/rpi-build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/mbed-cloud-client/1.0-r0/temp/run.do_configure.5566: 103: **cd: can't cd to /mbed-cloud-client-yocto-setup/rpi-build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/mbed-cloud-client/1.0-r0/git/mbed-cloud-client-example/__Yocto_Generic_YoctoLinux_mbedtls**
| WARNING: exit code 2 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /mbed-cloud-client-yocto-setup/rpi-build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/mbed-cloud-client/1.0-r0/temp/log.do_configure.5566)
ERROR: Task (/mbed-cloud-client-yocto-setup/poky/../meta-mbed-cloud-client/recipes-connectivity/mbed-cloud-client/mbed-cloud-client.bb:do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 311 tasks of which 257 didn't need to be rerun and 1 failed.

```

Tweak required:
```
cd ./rpi-build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/mbed-cloud-client/1.0-r0/git/mbed-cloud-client-example/pal-platform

python pal-platform.py  fullbuild --target Yocto_Generic_YoctoLinux_mbedtls --toolchain GCC
```
Reference https://cloud.mbed.com/docs/current/porting/using-the-pal-platform-utility.html 

Another error:

`ERROR: mbed-cloud-client-1.0-r0 do_package_qa: QA Issue: No GNU_HASH in the elf binary: '/mbed-cloud-client-yocto-setup/rpi-build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/mbed-cloud-client/1.0-r0/packages-split/mbed-cloud-client/opt/arm/mbedCloudClientExample.elf' [ldflags]
`

Tweak required
```
vi /mbed-cloud-client-yocto-setup/poky/../meta-mbed-cloud-client/recipes-connectivity/mbed-cloud-client/mbed-cloud-client.bb
INSANE_SKIP_${PN} = "ldflags"
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2688

**Comment by JaniSuonpera** [comment]
Hi @yemkay

Please see https://cloud.mbed.com/docs/v1.2/connecting/tutorial-connect-rpi3.html

**Comment by JaniSuonpera** [comment]
Hi @yemkay,

There are latest updated documentation https://cloud.mbed.com/docs/current/connecting/linux-on-raspberry-pi-3.html. Please check.

**Comment by JaniSuonpera** [comment]
Hi @yemkay,

Did you succeed to make build with updated documentation?

**Comment by teetak01** [comment]
@yemkay I am closing this issue as we have released the https://github.com/ARMmbed/mbed-cloud-client-yocto-setup/releases/tag/1.4.0 with significant improvements. Please reopen/open a new issue if you still encounter problems. Thanks for the report.
