### ISSUE TITLE
Compatibility on Raspberry Pi 3 Model B+ 

### ISSUE THREAD

**Issue by yemkay** [ARMmbed/mbed-cloud-client-yocto-setup#9]
I built the image, flashed to SD card and started my Pi 3 Model B+. It wouldn't start up. The Led light turns red and blinks 8 times, pauses for a moment and then repeats the blinking. 

Does this mean the image is not compatible for this model of Pi?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2691

**Comment by JaniSuonpera** [comment]
Hi @yemkay, 

Current version based to Yocto branch Morty (version 2.2) where meta-raspberrypi does not support new model B+.  It is compatible with https://www.raspberrypi.org/products/raspberry-pi-3-model-b/.  Future release we going to update newer Yocto branch, which also support Raspberry Pi 3 Model B+.

**Comment by JaniSuonpera** [comment]
Hi  @yemkay Latest changes from Friday includes support for Raspberry Pi 3 Model B+.  This is also working with Raspberry Pi 3 Model B.
